name: CI for Automation Project

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear Node.js cache
        run: |
          sudo apt-get remove nodejs
          sudo apt-get purge nodejs
          sudo apt-get install -y nodejs

      - name: Set up Node.js (version 20)
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: false  # Prevent using any old cached Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --force

      - name: Run Playwright API tests
        run: npx playwright test --project="API Tests"

      - name: Run Playwright UI tests
        run: npx playwright test --project="UI Tests"
