name: CI for Automation Project

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install --force
          npx playwright install chromium
          echo "Playwright browsers installed!"

      - name: Run Playwright API tests
        run: npx playwright test --project="API Tests"

      - name: Run Playwright UI tests
        run: npx playwright test --project="UI Tests"
